export const LEGAL_CONTRACT_REVIEW_ROUTE = 'legalContractReview'
export const LEGAL_CONTRACT_REVIEW_DETAIL_ROUTE = 'legalContractReviewDetail'
export const LEGAL_SMART_ARCHIVE_ROUTE = 'legalSmartArchive'
export const LEGAL_ASSISTANT_ROUTE = 'legalAssistant'
export const LEGAL_ASSISTANT_CHAT_ROUTE = 'legalAssistantChat'
