-- source_revision and source_text_hash are owned by 000099. This repair
-- migration intentionally has no destructive rollback: removing the columns
-- here would make a database that is correctly at 000099 invalid.
